### PR TITLE
Simple possibility to extend existing shortcuts with your own

### PR DESCRIPTION
**Pull request by andreruffert**
- feature: add extend possibility
  
  > Add functionality to extend (add/overwrite) the existing shortcuts by creating
  > `~/.display-shortcuts/shortcuts.json` containing your missing shortcuts.
- style: changed indent_style to `space`
  
  > All the existing code indention were with spaces. To don’t mix it up I
  > changed the indent_style to `space`.
  > If you added some new code the lines got an indention with tabs. Now
  > everything remains with spaces.

### CODE REVIEW

**Comment by khalillechelt** [comment]
Awesome, thanks man! Didn't even realize the space / tabs thing. Weird.

I like the display shortcuts configuration option but I think it would be nicer if you would extend the default JSON file with the configuration one instead of just concatenating because then you can also overwrite some configurations with your own description if you want. 

Also can you write a little test for that feature plz?

**Comment by andreruffert** [comment]
> I like the display shortcuts configuration option but I think it would be nicer if you would extend the default JSON file with the configuration one instead of just concatenating because then you can also overwrite some configurations with your own description if you want.

Word!
I made some quick changes just to make sure I got u right :)

_Example shortcuts.json_

``` JSON
[
  { "⌃ + A": "Overwrite a default, already existing shortcut description ✔" },
  { "ESC + T": "Overwrite another default, already existing shortcut description ✔" },
  { "uni-c": "Add a new awsm shortcut for unicorns ✔" }
]
```

> Also can you write a little test for that feature plz?

Of course the test will follow ✨

**Comment by khalillechelt** [comment]
OK great! I would say move `assignShortcuts` to its own file in a folder called `lib` and write some tests for the new functionality and we're good to go!

**Pull request merged**
